// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopMoviesService.proto

package com.example.topmovieproto;

public interface RatingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.topmovieproto.Rating)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string movieId = 1;</code>
   */
  String getMovieId();
  /**
   * <code>string movieId = 1;</code>
   */
  com.google.protobuf.ByteString
      getMovieIdBytes();

  /**
   * <code>int32 ratingVal = 2;</code>
   */
  int getRatingVal();
}
