// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopMoviesService.proto

package com.example.topmovieproto;

public interface TopMoviesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.topmovieproto.TopMoviesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  java.util.List<Rating>
      getRatingList();
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  Rating getRating(int index);
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  int getRatingCount();
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  java.util.List<? extends RatingOrBuilder>
      getRatingOrBuilderList();
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  RatingOrBuilder getRatingOrBuilder(
      int index);
}
