// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopMoviesService.proto

package com.example.topmovieproto;

public interface TopMoviesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.topmovieproto.TopMoviesRequest)
    com.google.protobuf.MessageOrBuilder {
}
