// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopMoviesService.proto

package com.example.topmovieproto;

public final class TopMoviesServiceOuterClass {
  private TopMoviesServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_topmovieproto_TopMoviesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_topmovieproto_TopMoviesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_topmovieproto_TopMoviesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_topmovieproto_TopMoviesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_topmovieproto_Rating_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_topmovieproto_Rating_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026TopMoviesService.proto\022\031com.example.to" +
      "pmovieproto\"\022\n\020TopMoviesRequest\"F\n\021TopMo" +
      "viesResponse\0221\n\006rating\030\001 \003(\0132!.com.examp" +
      "le.topmovieproto.Rating\",\n\006Rating\022\017\n\007mov" +
      "ieId\030\001 \001(\t\022\021\n\tratingVal\030\002 \001(\0052z\n\020TopMovi" +
      "esService\022f\n\tTopMovies\022+.com.example.top" +
      "movieproto.TopMoviesRequest\032,.com.exampl" +
      "e.topmovieproto.TopMoviesResponseB\002P\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_topmovieproto_TopMoviesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_topmovieproto_TopMoviesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_topmovieproto_TopMoviesRequest_descriptor,
        new String[] { });
    internal_static_com_example_topmovieproto_TopMoviesResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_topmovieproto_TopMoviesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_topmovieproto_TopMoviesResponse_descriptor,
        new String[] { "Rating", });
    internal_static_com_example_topmovieproto_Rating_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_topmovieproto_Rating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_topmovieproto_Rating_descriptor,
        new String[] { "MovieId", "RatingVal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
