// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TopMoviesService.proto

package com.example.topmovieproto;

/**
 * Protobuf type {@code com.example.topmovieproto.TopMoviesResponse}
 */
public  final class TopMoviesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.topmovieproto.TopMoviesResponse)
        com.example.topmovieproto.TopMoviesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TopMoviesResponse.newBuilder() to construct.
  private TopMoviesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TopMoviesResponse() {
    rating_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TopMoviesResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              rating_ = new java.util.ArrayList<Rating>();
              mutable_bitField0_ |= 0x00000001;
            }
            rating_.add(
                input.readMessage(Rating.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        rating_ = java.util.Collections.unmodifiableList(rating_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TopMoviesServiceOuterClass.internal_static_com_example_topmovieproto_TopMoviesResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TopMoviesServiceOuterClass.internal_static_com_example_topmovieproto_TopMoviesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TopMoviesResponse.class, Builder.class);
  }

  public static final int RATING_FIELD_NUMBER = 1;
  private java.util.List<Rating> rating_;
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  public java.util.List<Rating> getRatingList() {
    return rating_;
  }
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  public java.util.List<? extends RatingOrBuilder>
      getRatingOrBuilderList() {
    return rating_;
  }
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  public int getRatingCount() {
    return rating_.size();
  }
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  public Rating getRating(int index) {
    return rating_.get(index);
  }
  /**
   * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
   */
  public RatingOrBuilder getRatingOrBuilder(
      int index) {
    return rating_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < rating_.size(); i++) {
      output.writeMessage(1, rating_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < rating_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, rating_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TopMoviesResponse)) {
      return super.equals(obj);
    }
    TopMoviesResponse other = (TopMoviesResponse) obj;

    boolean result = true;
    result = result && getRatingList()
        .equals(other.getRatingList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRatingCount() > 0) {
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRatingList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TopMoviesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopMoviesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TopMoviesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopMoviesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopMoviesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TopMoviesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TopMoviesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TopMoviesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.topmovieproto.TopMoviesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.topmovieproto.TopMoviesResponse)
          TopMoviesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TopMoviesServiceOuterClass.internal_static_com_example_topmovieproto_TopMoviesResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TopMoviesServiceOuterClass.internal_static_com_example_topmovieproto_TopMoviesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TopMoviesResponse.class, Builder.class);
    }

    // Construct using com.example.topmovieproto.TopMoviesResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRatingFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (ratingBuilder_ == null) {
        rating_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ratingBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TopMoviesServiceOuterClass.internal_static_com_example_topmovieproto_TopMoviesResponse_descriptor;
    }

    @Override
    public TopMoviesResponse getDefaultInstanceForType() {
      return TopMoviesResponse.getDefaultInstance();
    }

    @Override
    public TopMoviesResponse build() {
      TopMoviesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TopMoviesResponse buildPartial() {
      TopMoviesResponse result = new TopMoviesResponse(this);
      int from_bitField0_ = bitField0_;
      if (ratingBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          rating_ = java.util.Collections.unmodifiableList(rating_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rating_ = rating_;
      } else {
        result.rating_ = ratingBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TopMoviesResponse) {
        return mergeFrom((TopMoviesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TopMoviesResponse other) {
      if (other == TopMoviesResponse.getDefaultInstance()) return this;
      if (ratingBuilder_ == null) {
        if (!other.rating_.isEmpty()) {
          if (rating_.isEmpty()) {
            rating_ = other.rating_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRatingIsMutable();
            rating_.addAll(other.rating_);
          }
          onChanged();
        }
      } else {
        if (!other.rating_.isEmpty()) {
          if (ratingBuilder_.isEmpty()) {
            ratingBuilder_.dispose();
            ratingBuilder_ = null;
            rating_ = other.rating_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ratingBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRatingFieldBuilder() : null;
          } else {
            ratingBuilder_.addAllMessages(other.rating_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TopMoviesResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TopMoviesResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Rating> rating_ =
      java.util.Collections.emptyList();
    private void ensureRatingIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        rating_ = new java.util.ArrayList<Rating>(rating_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Rating, Rating.Builder, RatingOrBuilder> ratingBuilder_;

    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public java.util.List<Rating> getRatingList() {
      if (ratingBuilder_ == null) {
        return java.util.Collections.unmodifiableList(rating_);
      } else {
        return ratingBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public int getRatingCount() {
      if (ratingBuilder_ == null) {
        return rating_.size();
      } else {
        return ratingBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Rating getRating(int index) {
      if (ratingBuilder_ == null) {
        return rating_.get(index);
      } else {
        return ratingBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder setRating(
        int index, Rating value) {
      if (ratingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingIsMutable();
        rating_.set(index, value);
        onChanged();
      } else {
        ratingBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder setRating(
        int index, Rating.Builder builderForValue) {
      if (ratingBuilder_ == null) {
        ensureRatingIsMutable();
        rating_.set(index, builderForValue.build());
        onChanged();
      } else {
        ratingBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder addRating(Rating value) {
      if (ratingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingIsMutable();
        rating_.add(value);
        onChanged();
      } else {
        ratingBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder addRating(
        int index, Rating value) {
      if (ratingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRatingIsMutable();
        rating_.add(index, value);
        onChanged();
      } else {
        ratingBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder addRating(
        Rating.Builder builderForValue) {
      if (ratingBuilder_ == null) {
        ensureRatingIsMutable();
        rating_.add(builderForValue.build());
        onChanged();
      } else {
        ratingBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder addRating(
        int index, Rating.Builder builderForValue) {
      if (ratingBuilder_ == null) {
        ensureRatingIsMutable();
        rating_.add(index, builderForValue.build());
        onChanged();
      } else {
        ratingBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder addAllRating(
        Iterable<? extends Rating> values) {
      if (ratingBuilder_ == null) {
        ensureRatingIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rating_);
        onChanged();
      } else {
        ratingBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder clearRating() {
      if (ratingBuilder_ == null) {
        rating_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ratingBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Builder removeRating(int index) {
      if (ratingBuilder_ == null) {
        ensureRatingIsMutable();
        rating_.remove(index);
        onChanged();
      } else {
        ratingBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Rating.Builder getRatingBuilder(
        int index) {
      return getRatingFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public RatingOrBuilder getRatingOrBuilder(
        int index) {
      if (ratingBuilder_ == null) {
        return rating_.get(index);  } else {
        return ratingBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public java.util.List<? extends RatingOrBuilder>
         getRatingOrBuilderList() {
      if (ratingBuilder_ != null) {
        return ratingBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(rating_);
      }
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Rating.Builder addRatingBuilder() {
      return getRatingFieldBuilder().addBuilder(
          Rating.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public Rating.Builder addRatingBuilder(
        int index) {
      return getRatingFieldBuilder().addBuilder(
          index, Rating.getDefaultInstance());
    }
    /**
     * <code>repeated .com.example.topmovieproto.Rating rating = 1;</code>
     */
    public java.util.List<Rating.Builder>
         getRatingBuilderList() {
      return getRatingFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Rating, Rating.Builder, RatingOrBuilder>
        getRatingFieldBuilder() {
      if (ratingBuilder_ == null) {
        ratingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Rating, Rating.Builder, RatingOrBuilder>(
                rating_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        rating_ = null;
      }
      return ratingBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.topmovieproto.TopMoviesResponse)
  }

  // @@protoc_insertion_point(class_scope:com.example.topmovieproto.TopMoviesResponse)
  private static final TopMoviesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TopMoviesResponse();
  }

  public static TopMoviesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TopMoviesResponse>
      PARSER = new com.google.protobuf.AbstractParser<TopMoviesResponse>() {
    @Override
    public TopMoviesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TopMoviesResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TopMoviesResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TopMoviesResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public TopMoviesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

